apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: two-sources
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: my-task
  sources:
    - repoURL: https://github.com/OpsMx/argo-training.git
      path: data/two-source/source-one
      targetRevision: HEAD
    - repoURL: https://github.com/OpsMx/argo-training.git
      path: data/two-source/source-two
      targetRevision: HEAD
